### ISSUE TITLE
If unzipped files already exist, give us an option to specify to override or not

### ISSUE THREAD

**Issue by Macleykun** [TonyBogdanov/zip#1]
Got this error when trying to unzip something in a location that had some files already:

replace ./somethingt.png? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)

**Comment by TonyBogdanov** [comment]
I didn't think anyone was using this package but me.
It is just a simple Alpine-based image with `zip` installed, meaning you can achieve your goal with CLI arguments:

```
-f  freshen existing files, create none
-n  never overwrite existing files         
-q  quiet mode (-qq => quieter)
-o  overwrite files WITHOUT prompting
```

Example:
```shell
unzip -qq -o ./archive.zip -d ./target
```

**Comment by Macleykun** [comment]
Oooh perfect thanks!
I wasn’t sure if zip was actually installed on Ubuntu latest, hence I found your action which felt easier and faster :p might be wrong 

thanks for the tip!
